spring.application.name=demo

# Port Binding for Render (0.0.0.0 is mandatory)
server.port=${PORT:10000}
server.address=0.0.0.0

# Database Configuration (Direct Internal URL - Fast & No Firewall)
spring.datasource.url=jdbc:postgresql://dpg-d89f36m7r5hc73df0kf0-a:5432/portfolio_db_new_2tbv
spring.datasource.username=portfolio_db_new_2tbv_user
spring.datasource.password=vlRqkDI33FaNkDcVc21wICtGaBljvvYT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.auto_quote_keyword=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashmit.zanzote.dev@gmail.com
spring.mail.password=wash wgkc kstu dopq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Enable JavaMail debug logs
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# SMTP Timeouts (prevents hanging)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Hikari Pool Settings for Render Stability
spring.datasource.hikari.connection-timeout=30000
# Maximum pool size reduced to 3 to save RAM and prevent OOM Kill
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=15000
