spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=Ashmit@1203*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.auto_quote_keyword=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashmit.zanzote.dev@gmail.com
spring.mail.password=dgvb egbj hgni ixdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Enable JavaMail debug logs
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# SMTP Timeouts (prevents hanging)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000